//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMnagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocateClassRoom
    {
        public int AllocateClassRoomId { get; set; }
        public int DeptId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public string RoomNo { get; set; }
        public string Day { get; set; }
        public string FromAMPM { get; set; }
        public string ToAMPM { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
    }
}
