//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMnagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssignToTeacher
    {
        public int CourseAssignToTeacherId { get; set; }
        public int CourseId { get; set; }
        public int DeptId { get; set; }
        public int TeacherId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
