//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace UniversityMnagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.CourseAssignToTeachers = new HashSet<CourseAssignToTeacher>();
        }
    
        public int TeacherId { get; set; }
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Email ID")]
        [Remote(action: "EmailExists", controller: "Teacher", ErrorMessage = "This Code Exists, Try new One")]
        [Display(Name = "Teachers Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Contact")]
        [Remote(action: "ContactExists", controller: "Teacher", ErrorMessage = "This Code Exists, Try new One")]
        [Display(Name = "Teachers Contact")]
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public int CreditTobeTaken { get; set; }
        public string Address { get; set; }
        public int DeptId { get; set; }
    
        public virtual ICollection<CourseAssignToTeacher> CourseAssignToTeachers { get; set; }
        public virtual Department Department { get; set; }
    }
}
